version: "3.3"

services:
    png:
        build:
            context: .
            dockerfile: ./docker/png/Dockerfile
        image: luizeof/image-optimizer
        volumes:
            - ./source:/var/workdir
    jpg:
        build:
            context: .
            dockerfile: ./docker/jpg/Dockerfile
        image: pockost/jpegoptim
        volumes:
            - ./source:/app
